### ISSUE TITLE
gAperture hard crashes when no exposure time found in database.

### ISSUE THREAD

**Issue by scfleming** [cmillion/gPhoton#121]
Example: python gAperture.py -b NUV -r 294.9237200 -d 47.2499900

Traceback (most recent call last):                          
  File "/Users/fleming/MY_PYTHON_PROGRAMS/gPhoton/gAperture.py", line 169, in <module>
    maskradius=args.maskradius,sigmaclip=args.sigmaclip)
  File "/Users/fleming/MY_PYTHON_PROGRAMS/gPhoton/gAperture.py", line 35, in gAperture
    maskradius=maskradius, sigmaclip=sigmaclip)
  File "/Users/fleming/Work/GALEX/gPhoton/REPO/gPhoton/source/curvetools.py", line 345, in write_curve
    test=pd.DataFrame({'t0':data['t0'],'t1':data['t1'],
KeyError: 't0'

There is a FIXME stub in the source code to handle this better.  Printing and logging an error message saying no exposure time exists and then exiting cleaning is sufficient.

**Comment by cmillion** [comment]
Could not reproduce.

python ./gFind.py -b NUV -r 22 -d 10
No NUV exposure time in database.

python ./gAperture.py -b NUV -r 22 -d 10 -a 0.0001
[]
AB Magnitudes:               
[]
