### ISSUE TITLE
Error in gMap: "events" returned as an empty list.

### ISSUE THREAD

**Issue by scfleming** [cmillion/gPhoton#154]
Command:
gMap(band='NUV', skypos=[7.85862,-44.63686], stepsz=30., skyrange=[0.0333333333333,0.0333333333333], cntfile='\<some file\>', cntcoaddfile='\<some other file\>', overwrite=True, verbose=3)

Here's the last line before the failure (events is an empty list, but the code is trying to access stuff inside it):

http://masttest.stsci.edu/portal/Mashup/MashupQuery.asmx/GalexPhotonListQueryTest?query=select time,ra,dec,xi,eta,x,y from GPFCore.dbo.fGetObjFromRectNUVAllColumns(7.84195333333335,7.87528666666665,-44.65352666666665,-44.62019333333335,844117081995,844117181995,0)&format=json&timeout={}
Traceback (most recent call last):
  File "wd_0029-449_coadd.py", line 7, in <module>
    main()
  File "wd_0029-449_coadd.py", line 4, in main
    gMap(band='NUV', skypos=[7.85862,-44.63686], stepsz=30., skyrange=[0.0333333333333,0.0333333333333], cntfile='/data2/fleming/GPHOTON_OUTPUT/LIGHTCURVES/WHITE_DWARFS/WD_0029-449/wd_0029-449_count_movie.fits', cntcoaddfile='/data2/fleming/GPHOTON_OUTPUT/LIGHTCURVES/WHITE_DWARFS/WD_0029-449/wd_0029-449_count_coadd.fits', overwrite=True, verbose=3)
  File "/home/fleming/MY_PYTHON_PROGRAMS/gPhoton/gPhoton/gMap.py", line 41, in gMap
    write_int_coadd=write_int_coadd)
  File "/home/fleming/MY_PYTHON_PROGRAMS/gPhoton/gPhoton/imagetools.py", line 255, in write_images
    response=True if i in ['int','int_coadd'] else False)
  File "/home/fleming/MY_PYTHON_PROGRAMS/gPhoton/gPhoton/imagetools.py", line 236, in create_image
    coadd=coadd,response=response,hdu=hdu,retries=retries)
  File "/home/fleming/MY_PYTHON_PROGRAMS/gPhoton/gPhoton/imagetools.py", line 221, in movie
    response=response)
  File "/home/fleming/MY_PYTHON_PROGRAMS/gPhoton/gPhoton/imagetools.py", line 125, in integrate_map
    verbose=verbose)
  File "/home/fleming/MY_PYTHON_PROGRAMS/gPhoton/gPhoton/imagetools.py", line 92, in makemap
    events = {'t':photons[:,0 ]/tscale, 'ra':photons[:,1], 'dec':photons[:,2],
IndexError: too many indices for array

**Comment by cmillion** [comment]
There really weren't any photons in that region / time range. Added an IndexError exception that just returns a blank image in this case. I actually already had a naive check for this, but it happened _after_ the indexing, which made it useless.
