### ISSUE TITLE
error in compute_shutter

### ISSUE THREAD

**Issue by scfleming** [cmillion/gPhoton#155]
I made the temporary work-around for #154, so I'm not sure if this is related or a new bug, here's the command being run:

gMap(band='NUV', skypos=[52.20308,-27.31683], stepsz=30., skyrange=[0.0333333333333,0.0333333333333], cntfile='\<some file\>', cntcoaddfile='\<some other file\>', overwrite=True, verbose=3)

http://masttest.stsci.edu/portal/Mashup/MashupQuery.asmx/GalexPhotonListQueryTest?query=select time,ra,dec,xi,eta,x,y from GPFCore.dbo.fGetObjFromRectNUVAllColumns(52.18641333333335,52.21974666666665,-27.33349666666665,-27.300163333333348,975864856995,975864956995,0)&format=json&timeout={}
Traceback (most recent call last):911.995, 814509941.995]]  
  File "wd_0326-273_coadd.py", line 7, in <module>
    main()
  File "wd_0326-273_coadd.py", line 4, in main
    gMap(band='NUV', skypos=[52.20308,-27.31683], stepsz=30., skyrange=[0.0333333333333,0.0333333333333], cntfile='/data2/fleming/GPHOTON_OUTPUT/LIGHTCURVES/WHITE_DWARFS/WD_0326-273/wd_0326-273_count_movie.fits', cntcoaddfile='/data2/fleming/GPHOTON_OUTPUT/LIGHTCURVES/WHITE_DWARFS/WD_0326-273/wd_0326-273_count_coadd.fits', overwrite=True, verbose=3)
  File "/home/fleming/MY_PYTHON_PROGRAMS/gPhoton/gPhoton/gMap.py", line 41, in gMap
    write_int_coadd=write_int_coadd)
  File "/home/fleming/MY_PYTHON_PROGRAMS/gPhoton/gPhoton/imagetools.py", line 261, in write_images
    retries=retries)
  File "/home/fleming/MY_PYTHON_PROGRAMS/gPhoton/gPhoton/imagetools.py", line 43, in movie_tbl
    verbose=verbose,retries=retries))
  File "/home/fleming/MY_PYTHON_PROGRAMS/gPhoton/gPhoton/dbasetools.py", line 142, in compute_exptime
    retries=retries)
  File "/home/fleming/MY_PYTHON_PROGRAMS/gPhoton/gPhoton/dbasetools.py", line 114, in exposure
    shutter = compute_shutter(band,trange,verbose=verbose,retries=retries)
  File "/home/fleming/MY_PYTHON_PROGRAMS/gPhoton/gPhoton/dbasetools.py", line 108, in compute_shutter
    band,trange[0],trange[1])),dtype='float64')[:,0]/gQuery.tscale)
IndexError: too many indices for array

**Comment by cmillion** [comment]
I think this is related to #132. It's trying to compute the exposure over _zero_ time range. Just pushed a fix for it to v1.25.5 that prevents the error. But the real problem is that it shouldn't get zero time ranges, so I'm still working on that part.

**Comment by scfleming** [comment]
@cmillion I'm still getting this error at the same location after pulling 1.25.5, so the fix made for #132 apparently did not address this issue.

**Comment by cmillion** [comment]
Ok. I'll dig deeper.

**Comment by cmillion** [comment]
I've added an IndexError exception to cover the fact that when no global events are available within a time range, the entire time range should be considered "shuttered." This shouldn't pop up again.
