### ISSUE TITLE
Hard crash in gAperture.

### ISSUE THREAD

**Issue by scfleming** [cmillion/gPhoton#194]
Running CR Dra NUV through gAperture and got this:

Traceback (most recent call last):.                         
  File "cr_dra_lc.py", line 25, in <module>
    main()
  File "cr_dra_lc.py", line 21, in main
    gAperture(band='NUV', skypos=[244.27247, 55.268069], stepsz=30., csvfile='cr_dra_lc_nuv_newapt.csv', maxgap=1800., overwrite=True, radius=0.0045, annulus=[0.0050,0.0060], detsize=1.25, verbose=3)
  File "/Users/fleming/MY_PYTHON_PROGRAMS/gPhoton/gAperture.py", line 39, in gAperture
    minimal_output=minimal_output)
  File "/Users/fleming/MY_PYTHON_PROGRAMS/gPhoton/curvetools.py", line 405, in write_curve
    photonfile=photonfile, detsize=detsize)
  File "/Users/fleming/MY_PYTHON_PROGRAMS/gPhoton/curvetools.py", line 391, in getcurve
    stepsz=stepsz, verbose=verbose, coadd=coadd)
  File "/Users/fleming/MY_PYTHON_PROGRAMS/gPhoton/curvetools.py", line 295, in quickmag
    if np.isnan(data['t']):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

FUV from CR Dra did not yield this error.  Working on it now.

**Comment by cmillion** [comment]
fixed in the v1.27.0 branch
