### ISSUE TITLE
gMap not returning data where gFind does

### ISSUE THREAD

**Issue by scfleming** [cmillion/gPhoton#212]
```
from gPhoton.gMap import gMap
from gPhoton.gFind import gFind
skypos = [271.35442, 23.12095]
gMap("NUV", cntfile='test.fits', coadd=True,skypos=skypos, overwrite=True,skyrange=[600./3600., 600./3600.],verbose=3,detsize=1.25)
gFind(skypos=skypos,detsize=1.25)
```
gFInd says there's data here:

NUV: 2866.0s (raw) in 2 exposures.

But then gMap doesn't find the same thing apparently...

Coadding across []
/Users/fleming/MY_PYTHON_PROGRAMS/gPhoton/imagetools.py:302: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  img = np.zeros(imsz)
Traceback (most recent call last):
  File "make_coadds.py", line 30, in <module>
    make_coadds()
  File "make_coadds.py", line 27, in make_coadds
    skyrange=[600./3600., 600./3600.],verbose=3,detsize=1.25)
  File "/Users/fleming/MY_PYTHON_PROGRAMS/gPhoton/gMap.py", line 126, in gMap
    write_int_coadd=write_int_coadd, detsize=detsize)
  File "/Users/fleming/MY_PYTHON_PROGRAMS/gPhoton/imagetools.py", line 630, in write_images
    True if i in ['int', 'int_coadd'] else False))
  File "/Users/fleming/MY_PYTHON_PROGRAMS/gPhoton/imagetools.py", line 538, in create_image
    detsize=detsize)
  File "/Users/fleming/MY_PYTHON_PROGRAMS/gPhoton/imagetools.py", line 447, in movie
    detsize=detsize)
  File "/Users/fleming/MY_PYTHON_PROGRAMS/gPhoton/imagetools.py", line 312, in integrate_map
    for i in np.arange(trange[0], trange[1], step):
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by cmillion** [comment]
My initial guess is that this is probably caused by the inconsistent detrad issue #210.

**Comment by cmillion** [comment]
It's not the same thing as #210. It appears to be some issue with the skyrange parameter.
