### ISSUE TITLE
Error when checking ObsType results in IndexError.

### ISSUE THREAD

**Issue by scfleming** [cmillion/gPhoton#221]
# **Reproduce:**
    id = "wd_1258+013"
    ra = 195.29383
    dec = 1.1277906
    ap = 19. / 3600.
    rin = 20.5 / 3600.
    rout = 38. / 3600.
    pes = gAperture("FUV", [coord.ra.deg, coord.dec.deg], ap,
                        annulus=[rin, rout],
                        csvfile=id+"_30sec_fuv.csv", stepsz=30., verbose=3,
                        overwrite=True, detsize=1.25)
**# Error:**
Traceback (most recent call last):
  File "find-map-ap.py", line 50, in <module>
    find_map_ap()
  File "find-map-ap.py", line 45, in find_map_ap
    overwrite=True, detsize=1.25)
  File "/Users/fleming/MY_PYTHON_PROGRAMS/gPhoton/gAperture.py", line 123, in gAperture
    minimal_output=minimal_output)
  File "/Users/fleming/MY_PYTHON_PROGRAMS/gPhoton/curvetools.py", line 1135, in write_curve
    detsize=detsize)
  File "/Users/fleming/MY_PYTHON_PROGRAMS/gPhoton/curvetools.py", line 1038, in get_curve
    stepsz=stepsz, verbose=verbose, coadd=coadd)
  File "/Users/fleming/MY_PYTHON_PROGRAMS/gPhoton/curvetools.py", line 953, in quickmag
    lcurve['flags'] = getflags(band, bin_ix, lcurve, verbose=verbose)
  File "/Users/fleming/MY_PYTHON_PROGRAMS/gPhoton/curvetools.py", line 766, in getflags
    if caiwarning(band, ix, events, verbose=verbose):
  File "/Users/fleming/MY_PYTHON_PROGRAMS/gPhoton/curvetools.py", line 483, in caiwarning
    if ((dbt.obstype(t,obsdata=obsdata) is 'CAI')
  File "/Users/fleming/MY_PYTHON_PROGRAMS/gPhoton/dbasetools.py", line 701, in obstype
    return str(obsdata[0][0])
IndexError: list index out of range

This does not happen for other time bins (10 sec, 60 sec) or other bands (NUV 30 sec does not trigger this either).

The problem is that this query:
gQuery.getArray(gQuery.obstype_from_t(t))
where "t" = 766247233.54, returns with an empty list.

For now, I do a try:except on IndexError and return "Unknown" as ObsType to work around it.  A better fix / figuring out what's going on with the query should be done.

**Comment by scfleming** [comment]
Might also need to catch the problem in legnum() defined right below obstype() in dbasetools.py.
